yolk/valvat

- lib/valvat/checksum/fr.rb
- spec/valvat/checksum/fr_spec.rb
- spec/valvat/checksum_spec.rb
I added a French checksum validation algorithm as follows:
FR VAT numbers format:
'FR'+ 2 digits (as validation key ) + 9 digits (as SIREN), the first and/or the second value can also be a character – e.g. FRXX999999999
The French key is calculated as follow : Key = [ 12 + 3 * ( SIREN modulo 97 ) ] modulo 97, for example  : Key = [ 12 + 3 * ( 404,833,048 modulo 97 ) ] modulo 97 = [12 + 3*56] modulo 97 = 180 modulo 97 = 83 so the tax number for 404,833,048 is FR 83,404,833,048 
source from : www.insee.fr
> Add French checksum validations

- lib/valvat/checksum/cy.rb
- lib/valvat/checksum/ee.rb
- lib/valvat/checksum/hr.rb
- lib/valvat/checksum/hu.rb
- lib/valvat/checksum/lt.rb
- lib/valvat/checksum/mt.rb
- lib/valvat/checksum/ro.rb
- lib/valvat/syntax.rb
- spec/valvat/checksum/cy_spec.rb
- spec/valvat/checksum/ee_spec.rb
- spec/valvat/checksum/hr_spec.rb
- spec/valvat/checksum/hu_spec.rb
- spec/valvat/checksum/lt_spec.rb
- spec/valvat/checksum/mt_spec.rb
- spec/valvat/checksum/ro_spec.rb
- spec/valvat/checksum_spec.rb
- spec/valvat/syntax_spec.rb
* Some of the regexes were too permissive.
* Added checksum validation for a number of countries.
Sources:
[1](http://85.81.229.78/systems/DKVIES/-%20Arkiv/Algoritme%E6ndringer/VIES-VAT%20Validation%20Routines-v15.0.doc), [2](http://www.braemoor.co.uk/software/vat.shtml) (suggested [here](https://github.com/yolk/valvat/issues/41))
I skipped Switzerland as there is already [an existing PR](https://github.com/yolk/valvat/pull/45).
I tried to stick as much as possible to the existing style and testing practices.
> Improve regexes and checksum coverage

- lib/valvat/checksum/gb.rb
- spec/valvat/checksum/gb_spec.rb
Main purpose of this PR is to add checksum validation for GB vat numbers.
Used this [document](http://85.81.229.78/systems/DKVIES/-%20Arkiv/Algoritme%E6ndringer/VIES-VAT%20Validation%20Routines-v15.0.doc) as reference.
> Add support for GB vats checksum validation

- lib/valvat/utils.rb
- spec/valvat/utils_spec.rb
Hi,
First of all thanks for this nice library :)
I noticed a strange issue recently with some VAT numbers with spaces being normalized and others not. Turns out it was because they were using some unicode spaces like the [punctuation space.](https://www.compart.com/en/unicode/U+2008)
I think we can easily improve handling of these by stripping any kind of unknown chars instead of just the one listed in the normalize regexp so I did this in this MR and added a spec for a VAT number with various unwanted chars, not just the classic ones.
Let me know what you think!
> More tolerant normalize regexp to strip unicode spaces and more

- lib/valvat/checksum/si.rb
- spec/valvat/checksum/si_spec.rb
Also updated tests with the valid SI VAT ID SI26833921 to illustrate the
bug. Had to remove the invalid SI22511880 from the list of valid VAT IDs
in the tests as it's in fact invalid. I've double-checked the validity of
the SI VAT IDs at:
http://ec.europa.eu/taxation_customs/vies/
> Fix checksum computation for Slovenian VAT ID.

- lib/valvat/checksum/nl.rb
- spec/valvat/checksum/nl_spec.rb
From 1-1-2020 there will be new vat_identification numbers in the Netherlands for freelancers. 
The old number had 'privacy' sensitive information, and because of that every freelancer in the Netherlands received a new vat identification number without privacy sensitive information which is valid from 1-1-2020.
The new number does not validate according to the current '11' check, but instead validates with a '97' check. This check is now added with two examples in the specs.
The check needs to substitute the letters with a number (A=10, B=11, C=13 etc) and then the `total % 97` has to equal 1 to be a valid vat identification number.
From 1-1-2020 and forward this new number will also validate with VIES.
For non freelancers the old 11-check number still exists, thus the validation needs to …
> Validate new dutch 2020 freelancer vat identification number

- lib/valvat/lookup.rb
Seems like the service now redirects when requesting a VAT number lookup.
Fixes https://github.com/yolk/valvat/issues/73
> Follow redirects

- lib/valvat/lookup.rb
Seems that `http` URL started redirecting to `https`
```
❯ curl -v http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl
*   Trying 2a01:7080:24:100::666:30...
* TCP_NODELAY set
*   Trying 147.67.210.30...
* TCP_NODELAY set
* Connected to ec.europa.eu (2a01:7080:24:100::666:30) port 80 (#0)
> GET /taxation_customs/vies/checkVatService.wsdl HTTP/1.1
> Host: ec.europa.eu
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 307 Temporary Redirect
< Location: https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Proxy-Connection: close
< Connection: close
< Content-Length: 738
<
<HTML><HEAD>
<TITLE>Redirect</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR> …
```
> Use https instead of http for VIES_WSDL_URL

- gemfiles/activemodel-5
Follows the same schema as the other gemfiles which test the latest minor release, i.e.
https://github.com/yolk/valvat/blob/7313ee19fdb621472cab1b41c460e091175e2b21/gemfiles/activemodel-5#L4
> Test with Rails 5.2 instead of 5.0

- CHANGES.md
This PR fixes a link in the changelog.
This was probably just a missed edit when releasing 1.0.0.
> CHANGES: Compare 1.0.0...master in "dev" section

- lib/valvat/locales/fr.yml
In the French locale the current error message is written as if the message was standalone, instead of following the field name, as is the default with ActiveRecord.
Currently, if the field is called "Numéro de TVA":
```rb
record.errors.full_messages
```
With this change:
```rb
record.errors.full_messages
```
> Remove duplication on French error messages

- lib/valvat/syntax.rb
Make BE regex future proof.
Based on following communication from Belgian government:
We currently use numbers starting with 0: “0.xxx.xxx.xxx” (0-series). However, the 0-series is not infinite. Once this series is exhausted, enterprise numbers will be assigned with the first number being 1: “1.xxx.xxx.xxx” (1-series).
Today there are still 183,600 enterprise numbers of the 0-series available. We estimate that at least 140,000 enterprise numbers beginning with “0” will be used up in the coming year. However, new projects (such as SABE – “loading of foreign entities”) may cause the 0-series to be used up faster than expected and thus more quickly numbers from the 1-series will be put into use.
We therefore ask you, by 01/01/2023 at the latest:
if necessary, to adapt your applications …
> Update BE regex in syntax.rb

- lib/valvat/checksum/es.rb
- spec/valvat/checksum/es_spec.rb
Is some cases, Valvat was applying Legal Person rules to a Natural Person VAT, causing invalid NIF's to be validated (e.g: ESX65474207)
If the VAT starts with `/\A[KLMXYZ\d]/`, we should always validate as a natural person.
___ 
We also are missing a lot of more rules that the AEAT applies in his official validation library written in Java, I'm working on it on [es_vat_with_all_aeat_rules](https://github.com/KirtashW17/valvat/tree/es_vat_with_all_aeat_rules) but it will be a major change on Valvat::Checksum::ES.  I will open another PR once finished.
Rules: http://www.migoia.com/website/articulos/NIF.html
Official Library: https://ws024.juntadeandalucia.es/maven/repository/internal/com/aeat/valida/valnif/2.0.1/
> Fix for Spain natural person VAT Validation

- lib/valvat/checksum/es.rb
- spec/valvat/checksum/es_spec.rb
Applies more rules to SPAIN VAT Number validation:
- CIF: If first digit is in [ABCDEFG], check-digit can be both a letter or a number.
- CIF: If first digit is in [HJUV], check-digit MUST be a number.
- CIF: If first digit is in [NPQRSW], check-digit MUST be a letter.
- Adds rules for special NIF's [KLM]: First two digits must be between 01 and 56 (inclusive).
Based on official AEAT VAT validation Library written in Java:
- https://ws024.juntadeandalucia.es/maven/repository/internal/com/aeat/valida/valnif/2.0.1/
- http://www.migoia.com/website/articulos/NIF.html
I also did some JJUnit tests to confirm this behaviours of the official library:
- [ValNifTest.zip](https://github.com/yolk/valvat/files/9594013/ValNifTest.zip)
> Es VAT checksum validation with all AEAT rules

- README.md
The VIES web page appears to have been reworked a bit. The old link 404s.
> Fix VIES "Unavailability Shifts" link

- lib/valvat/checksum/fr.rb
- lib/valvat/syntax.rb
- spec/valvat/checksum/fr_spec.rb
When one of the two first characters is not numerical, we apply special validation rules.
Based on python-stdnum FR VAT validation: https://github.com/arthurdejong/python-stdnum
> Improvements for Valvat::Checksum::FR

- lib/valvat.rb
- spec/valvat_spec.rb
Fix https://github.com/yolk/valvat/issues/120
Implements equality for Valvat objects. Works with `==` and `eql?`, as recommended in this context (https://medium.com/@khalidh64/difference-between-eql-equal-in-ruby-2ffa7f073532)
> feat(vat): Valvat object equality

- .github/workflows/rubocop.yml
- .github/workflows/specs.yml
Also added `bundler-cache: true` to the rubocop workflow to make it simpler and more consistent with the specs workflow.
> Update checkout to v3 to resolve Node 12 deprecation warning.

- lib/valvat/checksum/es.rb
- spec/valvat/checksum/es_spec.rb
Hi,
I noticed that I've made a typo in the commit [5e54550](https://github.com/yolk/valvat/pull/115/commits/5e54550a13faef417341ddc6dabecc3d1f5b5928)  (PR #115).  I'm very sorry.
A parenthesis was not placed correctly, causing the validation to fail for certain valid VATs (specifically those whose digits `[1..2]` were `00`.)
> Fixes typo in Valvat::Checksum::ES

- lib/valvat/lookup/vies.rb
In the SOAP request body generation for the VIES VAT number validation, there was an incorrect usage of the `@vat` instance variable. 
This instance variable was used for the fields `requesterCountryCode` and `requesterVatNumber`. I assume that the actual instance variable should be `@requester`
> Fix incorrect variable usage in SOAP request body

- CHANGES.md
- valvat.gemspec
The rexml dependency has a [DoS vulnerability](https://github.com/ruby/rexml/security/advisories/GHSA-vg3r-rm7w-2xgh)
> Name: rexml
> Version: 3.2.6
> CVE: CVE-2024-35176
> GHSA: GHSA-vg3r-rm7w-2xgh
> Criticality: Medium
> URL: https://github.com/ruby/rexml/security/advisories/GHSA-vg3r-rm7w-2xgh
> Title: REXML contains a denial of service vulnerability
> Solution: upgrade to '>= 3.2.7'
- Update the runtime dependency version for rexml to use the latest version [3.3.1](https://github.com/ruby/rexml/releases/tag/v3.3.1).
- Noted the update in the change log.
> Updated rexml dependency version to resolve the DoS vulnerability.

- valvat.gemspec
The change made in https://github.com/yolk/valvat/commit/0a97d777cbc8196b72ef1d7fe8d2d3484f7fec3d removed the translations from the gem. I am not sure this was intended? This change adds them back.
> Add translations back to the gem

- README.md
- lib/valvat/configuration.rb
- lib/valvat/error.rb
- lib/valvat/hmrc/access_token.rb
- lib/valvat/lookup/base.rb
- lib/valvat/lookup/hmrc.rb
- lib/valvat/options.rb
- lib/valvat/utils.rb
- spec/valvat/hmrc/access_token_spec.rb
- spec/valvat/lookup/hmrc_spec.rb
- spec/valvat/lookup_spec.rb
- spec/valvat/options_spec.rb
- spec/valvat/utils_spec.rb
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-registered-companies-api/2.0 
Resolves issue - https://github.com/yolk/valvat/issues/137
> Support HMRC API V2

- lib/valvat/locales/it.yml
This PR finishes the Italian locale translation, by adding the missing `vies_down` correct translation :)
> Add vies_down translation on Italian locale
